model:
  target: "target_chuva"
  features:
    - "Temp. Ins. (C)"
    - "Umi. Ins. (%)"
    - "Pto Orvalho Ins. (C)"
    - "Pressao Ins. (hPa)"
    - "Vel. Vento (m/s)"
    - "Raj. Vento (m/s)"
    - "hora"
    - "pressao_media_3h"
    - "variacao_pressao_1h"
    - "delta_temp_3h"
    - "vento_x"
    - "vento_y"

  lgbm:
    n_estimators: 300
    learning_rate: 0.03
    max_depth: 7
    num_leaves: 50

  xgboost:
    n_estimators: 300
    learning_rate: 0.03
    max_depth: 7
    scale_pos_weight: "auto"
    subsample: 0.8

data:
  raw_path: "data/raw/station-brasilia.csv"
  processed_path: "data/processed/station-brasilia-processed.feather"
  test_size: 0.2
  freq_amostragem: "1H"
