model:
  target: "target_chuva"
  features:
    - "Temp. Ins. (C)"
    - "Temp. Max. (C)"
    - "Temp. Min. (C)"
    - "Umi. Ins. (%)"
    - "Umi. Max. (%)"
    - "Umi. Min. (%)"
    - "Pto Orvalho Ins. (C)"
    - "Pto Orvalho Max. (C)"
    - "Pto Orvalho Min. (C)"
    - "Pressao Ins. (hPa)"
    - "Pressao Max. (hPa)"
    - "Pressao Min. (hPa)"
    - "Vel. Vento (m/s)"
    - "Dir. Vento (m/s)"
    - "Raj. Vento (m/s)"
    - "Radiacao (KJ/m²)"
    - "hora"
    - "pressao_media_30min"
    - "variacao_pressao_15min"
    - "vento_x"
    - "vento_y"

  lgbm:
    n_estimators: 300
    learning_rate: 0.03
    max_depth: 7
    num_leaves: 50

  xgboost:
    n_estimators: 300
    learning_rate: 0.03
    max_depth: 7
    scale_pos_weight: "auto"
    subsample: 0.8

data:
  raw_path: "data/raw/station-brasilia.csv"
  processed_path: "data/processed/station-brasilia-processed.feather"
  test_size: 0.2
